steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/qwiklabs-gcp-03-46d285fd8864/github.com/vineetson/ap:783a2ca6e0a3d4009eacd98640d5bf0610aabaa5:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/qwiklabs-gcp-03-46d285fd8864/github.com/vineetson/ap:783a2ca6e0a3d4009eacd98640d5bf0610aabaa5:$SHORT_SHA', '.']
    
